version: "3"
services:
  postgres_db:
    image: postgres:13.1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=noaa_etl
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=noaa_etl

